{% set version = "1.2.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gmedian
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Gmedian_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Gmedian/Gmedian_{{ version }}.tar.gz
  sha256: 5378666a91de7a7bed078626869362ed5f0d0587dd5e78b1ec3d54e249b92e55

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rspectra
    - r-rcpp >=0.12.6
    - r-rcpparmadillo
    - r-robustbase
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rspectra
    - r-rcpp >=0.12.6
    - r-rcpparmadillo
    - r-robustbase

test:
  commands:
    - $R -e "library('Gmedian')"           # [not win]
    - "\"%R%\" -e \"library('Gmedian')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Gmedian
  license: GPL-2.0-or-later
  summary: Fast algorithms for robust estimation with large samples of multivariate observations. Estimation of the geometric median, robust k-Gmedian clustering, and robust PCA based on the Gmedian covariation matrix.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
